apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- app.yaml
- app-svc.yaml
namespace: default
images:
- name: sample-python-app
  newName: nikhilk21/sample-python-app
  newTag: 86e6d3175a02bb9664042fd13d4cbe45fe55dc82
