apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- app.yaml
- app-svc.yaml
namespace: default
images:
- name: sample-python-app
  newName: nikhilk21/sample-python-app
  newTag: ef4d6f7d390dc12b04e6b854b36a9977f4b1b6fa
