name : ci
on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'manifests/**'
      - '**/*.gitattributes'
      - '**/*.gitignore'
      - '**/*.md'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: nikhilk21/sample-python-app:latest
